apiVersion: apps/v1
kind: Deployment
metadata:
  name: ajerlo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ajerlo
  template:
    metadata:
      labels:
        app: ajerlo
    spec:
      containers:
        - name: ajerlo-container
          image: ajerlo-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: RUN_MIGRATIONS
              value: "true"
            - name: DEBUG
              value: "1"
            - name: ACCOUNTS_API_BASE
              value: "http://accounts-service:8000/api"
            - name: RENTALS_API_BASE
              value: "http://rentals-service:8000/api/rentals"

