apiVersion: v1
kind: Service
metadata:
  name: ajerlo-frontend-service
  namespace: ajerlo
spec:
  selector:
    app: ajerlo-frontend
  ports:
    - protocol: TCP
      port: 80        # external
      targetPort: 80   # internal container port
