apiVersion: apps/v1
kind: Deployment
metadata:
  name: ajerlo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ajerlo-backend
  template:
    metadata:
      labels:
        app: ajerlo-backend
    spec:
      containers:
        - name: ajerlo-backend
          image: tamer1212/ajerlo-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "ajerlo.settings"
