apiVersion: apps/v1
kind: Deployment
metadata:
  name: rentals-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rentals-service
  template:
    metadata:
      labels:
        app: rentals-service
    spec:
      containers:
        - name: rentals-service
          image: tamer1212/rentals-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "rentals_service.settings"
