apiVersion: apps/v1
kind: Deployment
metadata:
  name: rentals
  namespace: ajerlo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rentals
  template:
    metadata:
      labels:
        app: rentals
    spec:
      containers:
      - name: rentals
        image: eece430-group9-rentals_service
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_HOST
          value: postgres-service
        - name: POSTGRES_DB
          value: ajerlo
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_PORT
          value: "5432"
        - name: DB_ENGINE
          value: postgres
        ports:
        - containerPort: 8000
